#!/usr/bin/python3

"""
A quick script to extract the text from a transcript generated by AWS Transcribe.
Download the transcript in JSON format and feed it to this script to get the text.
"""

import json
import sys

json_txt = open(sys.argv[1])
data = json.load(json_txt)

"""
# The JSON format is (roughly):
{
    'accountId': a big ID number
    'jobName': a string, what you named the job
    'status': hopefully, 'COMPLETED'
    'speaker_labels': if you enabled speaker identification, a list of timestamps
    'results': {
        'items': a list of dictionaries containing metadata of the form
        {
            'start_time': the starting timestamp for this word
            'end_time': the ending timestamp for this word
            'type': one of ('pronunciation', 'punctuation')
            'alternatives': a list of alternative words
        }
        'transcripts': a list of transcript dictionaries of the form
        {
            'transcript': giant string containing the actual transcription
        }
    }
}
"""
# Sadly, the JSON data does not link the timestamps to the offset
# in the transcript text, so it's pretty useless by itself.

# Just print the raw transcript text to stdout.
for transcript in data['results']['transcripts']:
    print(transcript['transcript'])
